/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joginhogooglegenio;

import java.applet.AudioClip;

/**
 *
 * @author TIAGO
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        //placar
        txtTente.setVisible(false);
        tente.setVisible(false);
        txtplacar.setVisible(false);
        txterr.setVisible(false);
        txtacer.setVisible(false);
        err.setVisible(false);
        acer.setVisible(false);
        
        btnPalpite.setVisible(false);
        f2.setVisible(false);
        txtVal.setVisible(false);
        img2.setVisible(false);
        balao.setVisible(false);
        lblFrase.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        txtVal = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        btnjogar = new javax.swing.JButton();
        img2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        balao = new javax.swing.JLabel();
        barra1 = new javax.swing.JPanel();
        barra2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtacer = new javax.swing.JLabel();
        txterr = new javax.swing.JLabel();
        acer = new javax.swing.JLabel();
        err = new javax.swing.JLabel();
        txtplacar = new javax.swing.JLabel();
        txtTente = new javax.swing.JLabel();
        tente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("JOGINHO GOOGLE GÊNIO ALLADIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        f2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        f2.setText("VALOR");
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 482, -1, 30));

        txtVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtVal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 75, 30));

        btnPalpite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPalpite.setForeground(new java.awt.Color(0, 0, 204));
        btnPalpite.setText("PALPITE");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 170, 40));

        btnjogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnjogar.setForeground(new java.awt.Color(0, 0, 255));
        btnjogar.setText("PLAY");
        btnjogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnjogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 170, 50));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagem acertou.png"))); // NOI18N
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 160));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/img1.JPG"))); // NOI18N
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        lblFrase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrase.setText("<html>ÓLA VOU PENSAR EM UM NUMERO DE 1 A 5 TENTE ADVINHAR:</html>");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, 90));

        balao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/balao.png"))); // NOI18N
        getContentPane().add(balao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        javax.swing.GroupLayout barra1Layout = new javax.swing.GroupLayout(barra1);
        barra1.setLayout(barra1Layout);
        barra1Layout.setHorizontalGroup(
            barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        barra1Layout.setVerticalGroup(
            barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 560));

        javax.swing.GroupLayout barra2Layout = new javax.swing.GroupLayout(barra2);
        barra2.setLayout(barra2Layout);
        barra2Layout.setHorizontalGroup(
            barra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        barra2Layout.setVerticalGroup(
            barra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 480, 10));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 170, 40));

        txtacer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtacer.setForeground(new java.awt.Color(0, 153, 51));
        txtacer.setText("ACERTOS:");
        getContentPane().add(txtacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        txterr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txterr.setForeground(new java.awt.Color(204, 0, 0));
        txterr.setText("ERROS:");
        getContentPane().add(txterr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        acer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        acer.setForeground(new java.awt.Color(0, 153, 0));
        acer.setText("0");
        getContentPane().add(acer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 50, 20));

        err.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        err.setForeground(new java.awt.Color(204, 0, 0));
        err.setText("0");
        getContentPane().add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 50, 20));

        txtplacar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtplacar.setText("PLACAR");
        getContentPane().add(txtplacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, -1));

        txtTente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTente.setForeground(new java.awt.Color(0, 0, 255));
        txtTente.setText("TENTATIVAS:");
        getContentPane().add(txtTente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        tente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tente.setForeground(new java.awt.Color(0, 0, 255));
        tente.setText("0");
        getContentPane().add(tente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 30, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnjogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjogarActionPerformed
        // TODO add your handling code here:
        
        //placar
        txtTente.setVisible(true);
        tente.setVisible(true);
        txtplacar.setVisible(true);
        txterr.setVisible(true);
        txtacer.setVisible(true);
        err.setVisible(true);
        acer.setVisible(true);
        
        btnPalpite.setVisible(true);
        f2.setVisible(true);
        txtVal.setVisible(true);
        btnjogar.setVisible(false);
        balao.setVisible(true);
        lblFrase.setVisible(true);
        lblFrase.setText("<html>VOU PENSAR EM UM NUMERO DE 1 A 5 TENTE ADVINHAR:</html>");
        
        //AUDIO1
        AudioClip audio1;
        audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/audio1.wav"));
        audio1.play();
        
    }//GEN-LAST:event_btnjogarActionPerformed

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        
        double n = 1 + Math.random() * (5- 1);
        int v = (int) n;
        
        int num = Integer.parseInt(txtVal.getValue().toString());
        
        int t = (Integer.parseInt(tente.getText()));
        
        tente.setText(Integer.toString(t = t + 1));
        
        int a = (Integer.parseInt(acer.getText()));
        
        int e = (Integer.parseInt(err.getText()));
        
            if(num == v){
            acer.setText(Integer.toString(a = a + 1));
            img2.setVisible(true);
            img1.setVisible(false);
            lblFrase.setText("<html>PARABÉNS!!! VOCÊ ACERTOU O NUMERO QUE PENSEI!!!:</html>");
            //audio = audio 2
            AudioClip audio2;
            audio2 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/audio2.wav"));
            audio2.play();   
            }else{
                if(v == 5){
                err.setText(Integer.toString(e = e + 1));
                img2.setVisible(false);
                img1.setVisible(true);
                lblFrase.setText("<html>VOCÊ ERROU, EU PENSEI EM:  5  </html>");
                //audio= pensei 5
                AudioClip audio5;
                audio5 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/pensei5.wav"));
                audio5.play();
                }else{
                    if(v == 4){
                    err.setText(Integer.toString(e = e + 1));
                    img2.setVisible(false);
                    img1.setVisible(true);
                    lblFrase.setText("<html>VOCÊ ERROU, EU PENSEI EM:  4  </html>");
                    //audio= pensei 4
                    AudioClip audio4;
                    audio4 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/pensei4.wav"));
                    audio4.play();
                    }else{
                        if(v == 3){
                        err.setText(Integer.toString(e = e + 1));
                        img2.setVisible(false);
                        img1.setVisible(true);
                        lblFrase.setText("<html>VOCÊ ERROU, EU PENSEI EM:  3  </html>");
                        //audio= pensei 3
                        AudioClip audio3;
                        audio3 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/pensei3.wav"));
                        audio3.play();
                        }else{
                             if(v == 2){
                                err.setText(Integer.toString(e = e + 1));
                                img2.setVisible(false);
                                img1.setVisible(true);
                                lblFrase.setText("<html>VOCÊ ERROU, EU PENSEI EM:  2  </html>");
                                 //audio= pensei 3
                                AudioClip audio2;
                                audio2 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/pensei2.wav"));
                                audio2.play();
                                }else{
                                    err.setText(Integer.toString(e = e + 1));
                                    img2.setVisible(false);
                                    img1.setVisible(true);
                                    lblFrase.setText("<html>VOCÊ ERROU, EU PENSEI EM:  1  </html>");
                                    //audio= pensei 3
                                    AudioClip audio1;
                                    audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/pensei1.wav"));
                                   audio1.play();
                                   
                    }
                }
            }
        }        
    }                
    }//GEN-LAST:event_btnPalpiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acer;
    private javax.swing.JLabel balao;
    private javax.swing.JPanel barra1;
    private javax.swing.JPanel barra2;
    private javax.swing.JButton btnPalpite;
    private javax.swing.JButton btnjogar;
    private javax.swing.JLabel err;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel tente;
    private javax.swing.JLabel txtTente;
    private javax.swing.JSpinner txtVal;
    private javax.swing.JLabel txtacer;
    private javax.swing.JLabel txterr;
    private javax.swing.JLabel txtplacar;
    // End of variables declaration//GEN-END:variables
}
